### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by xdkaiin** [blaze33/droneWorld#6]
Attempted import error: 'Worker' is not exported from './terrain.worker.js'.

**Comment by blaze33** [comment]
Turns out I messed up the master branch one month ago after trying to update create-react-app to 3.0.0 (after yarn eject which kinda complicates solving this).
In the meantime you can checkout the 0.1.0 tag with git (git checkout 0.1.0).
Use node v10 because some dependency uses the node-sass version not yet compatible with node v12.
Sorry I wasn't aware people were actually trying out droneWorld ;)
